### PR TITLE
Add materials for 2023-11-20 session

### PR DESCRIPTION
**Pull request by mirenradia**
This adds a partially complete [Computational Thinking](https://computationalthinking.mit.edu/Fall23/) [HW2](https://computationalthinking.mit.edu/Fall23/homework/hw2/) so that attendees can follow along.

### CODE REVIEW

**Review by jatkinson1000 — CHANGES_REQUESTED** [review]
Could you create some sort of sub-structure (e.g. an MIT_homeworks directory or something) rather than just placing the notebook in the main repo please?

**Comment by giordano** [comment]
Might also be nice to add a `Project.toml` file to the directory like
```toml
[deps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
Pluto = "0.19.32"
julia = "1.9"
```
so that people can start the notebook in the right environment with `julia --project=.`.

**Comment by mirenradia** [comment]
For consistency with @giordano's suggestion of creating a `Project.toml` file, I've put the materials in the `src/` subdirectory. I don't really understand how julia projects work but I think the `julia_Study_Group.jl` file is required for the project to work.

**Review by jatkinson1000 — APPROVED** [review]
🚀🚀🚀

**Comment by giordano** [comment]
> I don't really understand how julia projects work

It's like virtual environments in Python.  Specifically, the `Project.toml` file is like a `Cargo.toml` file in Rust, or `package.json` in javascript: it defines the top-level dependencies of your environment.

> but I think the julia_Study_Group.jl file is required for the project to work.

Not really.  Actually, I'm not sure if that's needed if you add the name/uuid/version to the project, but you can also have a `Project.toml` without them in which case you don't need any extra file with specific names.

**Pull request merged**
